disabled_rules:
  - trailing_comma
  - force_cast
  - force_try

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

included:
  - Sources
  - Tests

excluded:
  - .build
  - DerivedData
  - Packages

line_length:
  warning: 140
  error: 200

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - ip
    - to
    - x
    - y

nesting:
  type_level: 3
  function_level: 3

reporter: "xcode"
